# Generated by Django 4.2 on 2023-04-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="created_on",
        ),
        migrations.AddField(
            model_name="todo",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
